name: Pelagios Network
markdown: kramdown
permalink: pretty

collections_dir: content
collections:
  activities:
    output: true
  case-studies:
    output: true
  partners:
    output: false
  events:
    output: true

sass:
  style: compact # possible values: nested expanded compact compressed
url: "https://pelagios.org" # the base hostname & protocol for your site
plugins:
  - jekyll-sitemap

# Google Analytics
google_analytics: UA-141761161-1
