name: Pelagios Network
markdown: kramdown
permalink: pretty

collections_dir: content
collections:
  activities:
    output: true
  case-studies:
    output: true
  partners:
    output: false
  events:
    output: true

sass:
  style: compact # possible values: nested expanded compact compressed
url: "https://pelagios.org" # the base hostname & protocol for your site
plugins:
  - jekyll-sitemap

# Google Analytics
google_analytics: UA-141761161-1

title: Pelagios Network
description: The Pelagios Network is a community of scholars, technologists, and cultural heritage professionals working together to make the world’s historical places and spaces more visible online.
keywords: Pelagios, network, history, archaeology, digital humanities
image: /assets/images/pelagios-logo.png
defaults:
  - scope:
      path: ""
    values:
      image: /assets/images/pelagioslogo.svg